### ISSUE TITLE
Render html

### ISSUE THREAD

**Issue by MarieEtienne** [AgrocampusDS/visualisation-laurine-yannis#1]
Il est inutile de déposer le html sur git, il sera généré automatiquement à partir de flexdashboard et placé dans la branche gh-pages lorsque vous poussez sur master. 
Vous pouvez voir le résultat sur https://agrocampusds.github.io/visualisation-laurine-yannis/flexdashboard.html après quelques minutes de propagation. SI vous avez besoin de package supplémenatire ouvrez une issue sur github et je vous indiquerai comment les ajouter.
Bon travail

**Comment by Yannis-Barba** [comment]
Très bien c'est noté, j'ai ajouté le fichier html dans le .gitignore

**Comment by MarieEtienne** [comment]
Il faut aussi faire un git rm flexdashboard.html   pour le supprimer du système de suivi. Il ne doit plus etre visible dans master sur github

**Comment by Yannis-Barba** [comment]
yes, c'est fait, je n'ai juste pas encore push les modifications
